📦 chore: initial settings (#2)
* 📦 chore: 메인, 디벨롭에서 커밋푸시 제한

* 📦 chore: 타입스크립트/버전 오류 해결

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,13 @@ pnpm lint
 
 echo "🚚 finished linting.."
 echo "✔ check branch before push"
+
+current_branch=$(git branch --show-current)
+
+restricted_branches="^(main|master|develop/.+)$"
+
+if [[ $current_branch =~ $restricted_branches ]]; then
+  echo "❌ You cannot commit on a restricted branch: $current_branch.."
+  echo "❌ Not allowed via pre-commit hook.."
+  exit 1
+fi
